name: Run OpenTofu check

on:
  - push

jobs:
  opentofu-check:
    name: Run OpenTofu check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Show version
        run: tofu -version

      - name: Run init
        run: |
          cd modules
          for f in * ; do
            if [ -d "$f" ] ; then
              cd $f
              tofu --init
              cd ..
            fi
          done

      - name: Run check format
        run: |
          tofu fmt -check -recursive -no-color

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Run OpenTofu check
